name: "[Dispatch] Sync CI"

on:
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: cloudforet-io
  repo: actions
  ref: master

jobs:
  owner_check:
    if: github.repository_owner == 'cloudforet-io'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  pull_workflows:
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: pull workflows
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          client_payload: '{"dest" : "${{ github.event.repository.name }}" , "sync_only" : "true"}'
          trigger_workflow: true
          wait_workflow: false
